name: Api

on:
  push: 
    tags:
      - v0.*.*
    branches: [ main, feat/*, feature/* ]
    paths:
        - 'api/**'

  workflow_dispatch:

env:
  app: api
  stage: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || 'dev' }}
 
jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build-ids.outputs.tag }}${{ steps.build-ids.outputs.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: |
          make build app=$app

      - name: Security Scan 
        uses: securego/gosec@master
        run: |
          make scan app=$app
          
  test:
    needs:
        - build
    
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Unit Tests
        run: |
          make test app=$app
